name: focus_me
description: Une application Flutter pour la gestion quotidienne des tâches avec notifications et statistiques.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  
  # Charts & Statistics
  fl_chart: ^0.66.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Animations
  flutter_animate: ^4.5.0
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Shared Preferences
  shared_preferences: ^2.2.2
  
  # UUID
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
